CvSiteHt21_Grupp34/CvSiteHt21_Grupp34/Controllers/CvController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;
using Data.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Services;
using Shared.ViewModels;

namespace CvSiteHt21_Grupp34.Controllers
{
    public class CvController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private CvService cvService = new CvService(System.Web.HttpContext.Current);

        // GET: Cv
        public ActionResult Index()
        {
            string user = User.Identity.GetUserId();
            ViewBag.ID = user;

            var context = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            var Cvs = context.GetCvs.ToList();
            return View(Cvs);
        }

        // GET: Cv/Details/5
        public ActionResult Details(string id)
        {
            var context = new ApplicationDbContext();

            Cv cv = context.GetCvs.Find(id);
            ApplicationUser user = context.Users.Find(cv.UserId);

            var files = Directory.GetFiles(Server.MapPath("~/Images/"));
            var cvImage = cv.ImageUrl;
            ViewBag.Path = ("~/Images/") + cvImage;

            var experience = cv.Experience;
            var education = cv.Education;
            var competence = cv.Competence;
            var image = "/Images/" + cv.ImageUrl;
            var name = user.UserName;
            var email = user.Email;
            var city = user.City;
            var username = user.Fullname;
            ViewBag.ID = user.Id;

            List<Project> project = context.GetProjects.ToList();
            List<UsersInProject> projectWithUsers = context.GetUsersInProjects.Where(x => x.ApplicationUserID == id).ToList();

            List<Project> projects = new List<Project>();
            foreach (var a in project)
                foreach (var b in projectWithUsers)
                {
                    if (a.ProjectId == b.ProjectId)
                    {
                        projects.Add(a);
                    }

                }
            CvViewModel CvView = new CvViewModel(competence, education, experience, image, name, email, city, projects, username);

            return View(CvView);
        }
    

        // GET: Cv/Create
        public ActionResult Create()
        {
            //ViewBag.UserId = new SelectList(db.Users, "Id", "Fullname");
            return View();
        }

        // POST: Cv/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CvViewModel model)
        {
            var context = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            try
            {
                if (ModelState.IsValid)
                {
                    var service = new CvService(System.Web.HttpContext.Current);

                    service.CreateNewCv(model);

                }
                return RedirectToAction("Index");
            }

            catch
            {

                return RedirectToAction("Index");

            }
        }

        // GET: Cv/Edit/5
        public ActionResult Edit(string id)
        {
            using (var context = new ApplicationDbContext())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Cv cv = context.GetCvs.Find(id);

                return View(cv);

            }

        }

        // POST: Cv/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Competence,Education,Experience,ImageUrl")] Cv cv)
        {
            using (var context = new ApplicationDbContext())

            {
                if (ModelState.IsValid)
                {

                    context.Entry(cv).State = EntityState.Modified;

                    context.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        // GET: Cv/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cv cv = db.GetCvs.Find(id);
            if (cv == null)
            {
                return HttpNotFound();
            }
            return View(cv);
        }

        // POST: Cv/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Cv cv = db.GetCvs.Find(id);
            db.GetCvs.Remove(cv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

CvSiteHt21_Grupp34/CvSiteHt21_Grupp34/Controllers/MessageController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using Data;
using Data.Models;
using Microsoft.AspNet.Identity;
using Services;
using Shared.ViewModels;

namespace CvSiteHt21_Grupp34.Controllers
{
    public class MessageController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private readonly MessageService service = new MessageService();

        // GET: Message
        public ActionResult Index()
        {
            var user = User.Identity.GetUserId();
            ViewBag.ID = user;

            var inbox = service.GetInbox(user);

            var listWithMessages = new List<MessageViewModel>();
            foreach (var msg in inbox)
            {
                var ViewModel = new MessageViewModel
                {
                    ReceiverId = user,
                    Sender = msg.Sender,
                    MessageId = msg.MessageId,
                    IsRead = msg.IsRead
                };
                var message = service.FindMessages(msg.MessageId);
                ViewModel.Content = message.Content;

                listWithMessages.Add(ViewModel);
            }

            return View(listWithMessages);
        }

        public ActionResult MarkAsRead(int id) //Tillåter en användare att markera ett meddelande som läst
        {
            service.Read(id);
            return RedirectToAction("Index");
        }

        // GET: Message/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var message = db.GetMessages.Find(id);
            if (message == null) return HttpNotFound();
            return View(message);
        }

        // GET: Message/Create
        public ActionResult Create(string id) //Tillåter en en användare att skicka ett meddelande till en annan användare
        {
            try
            {
                var senderId = User.Identity.GetUserId(); 
                var sender = db.Users.Find(senderId);
                var receiver = db.Users.Find(id);

                var receiverId = receiver.Id;
                var receiverName = receiver.Fullname;

                if (sender == null)
                {
                    var anonymous = new MessageInfo();
                    var anonymousMessage = anonymous.Sender = "Anonymous";
                    var anonymousViewModel = new MessageViewModel
                    {
                        Sender = anonymous.Sender,
                        ReceiverId = receiverId,
                        Receiver = receiverName
                    };
                    return View(anonymousViewModel);
                }

                var ViewModel = new MessageViewModel
                {
                    Sender = sender.Fullname,
                    ReceiverId = receiverId,
                    Receiver = receiverName
                };
                return View(ViewModel);
            }
            catch
            {
                return View("Index");
            }
        }

        // GET: Message/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var message = db.GetMessages.Find(id);
            if (message == null) return HttpNotFound();
            return View(message);
        }

        // POST: Message/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MessageId,Content,Date")] Message message)
        {
            if (ModelState.IsValid)
            {
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(message);
        }

        // GET: Message/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var message = db.GetMessages.Find(id);
            if (message == null) return HttpNotFound();
            return View(message);
        }

        // POST: Message/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var message = db.GetMessages.Find(id);
            db.GetMessages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CvSiteHt21_Grupp34/CvSiteHt21_Grupp34/Views/Cv/Create.cshtml
@model Data.Models.Cv

@{ ViewBag.Title = "Create"; }

<h2>Create Cv</h2>


@using (Html.BeginForm("Create", "Cv", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Competence, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Competence, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Competence, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Education, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Education, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Education, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Experience, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                <label>
                    Image
                </label>
            </div>
            <div class="col-md-offset-1 col-md-12">
                <input type="file" name="Image" value="Add file"/>
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-3 col-md-10">
            <input type="submit" value="Create" class="btn btn-default"/>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CvSiteHt21_Grupp34/CvSiteHt21_Grupp34/Views/Cv/Delete.cshtml
@model Data.Models.Cv

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cv</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Fullname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Competence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Competence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Cv", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CvSiteHt21_Grupp34/CvSiteHt21_Grupp34/Views/Cv/Details.cshtml
@model Shared.ViewModels.CvViewModel
@using System.Diagnostics
@using Data.Models
@using Data

@{
    ViewBag.Title = "Details";
    Layout = null;

}

<div style="padding-left: 6%">
    <br/>
    <h2>Cv details for: @Model.Username</h2>
    <hr/>
    <img src="@Model.ImageUrl" alt="Profile image" width="300" ;/>
    <br/>
    <br/>

    <dl class="dl-horizontal">
        <dt style="text-align: left !important">
            @Html.DisplayNameFor(model => model.User.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt style="text-align: left !important">
            @Html.DisplayNameFor(model => model.Competence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Competence)
        </dd>

        <dt style="text-align: left !important">
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt style="text-align: left !important">
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>
        <dt style="text-align: left !important">
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<h3 style="padding-left: 6%">Projects: </h3>
<table class="table">
    <tr>
        <th style="padding-left: 6%">
            Title
        </th>
        <th>
            Description
        </th>
    </tr>
    @foreach (var item in Model.Projects)
    {
        <tr>
            <td style="padding-left: 6%">
                @Html.DisplayFor(modelItem => item.Title)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
    }
</table>
<div style="padding-left: -6%">
    @{ Html.RenderAction("Create", "Message", new {id = ViewBag.Id}); }

</div>

CvSiteHt21_Grupp34/CvSiteHt21_Grupp34/Views/Cv/Edit.cshtml
@model Data.Models.Cv

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cv</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.Competence, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Competence, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Competence, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Education, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Education, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Education, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Experience, "", new {@class = "text-danger"})
            </div>
        </div>

        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.ImageUrl)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CvSiteHt21_Grupp34/CvSiteHt21_Grupp34/Views/Cv/Index.cshtml
@model IEnumerable<Data.Models.Cv>
@using Data
@using Microsoft.AspNet.Identity


@{
    ViewBag.Title = "Index";
}

<h2>List of Cvs</h2>
<br />


@{bool hasCv = false;
    foreach (var cv in Model)
    {
        if (cv.User.Id == User.Identity.GetUserId())
        {
            hasCv = true;
        }
    }
}

@if (User.Identity.IsAuthenticated && !hasCv)
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Competence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Experience)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Education)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var userId = User.Identity.GetUserId();
        if (User.Identity.IsAuthenticated || item.User.IsPrivate == false)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Fullname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Competence)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Experience)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Education)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
                </td>
                @if (userId == item.User.Id)
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.UserId })
                    </td>
                }

            </tr>
        }
    }

</table>